on: push

jobs:
  test:
    name: Testes de API Back-End
    runs-on: ubuntu-latest

    steps: 
      - name: Clonando repositório para a máquina
        uses: actions/checkout@v4

      - name: Configurando Python na máquina
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalação das Dependências do Projeto 
        run: |
          pip install robotframework
          pip install robotframework-requests

      - name: Executando os Testes no Robot 
        run: |
          robot --name "Resultado Testes Api" --outputdir results/ tests/

      - name: Salvando Resultado dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: robot-framework-report
          path: results/

      - name: Publicando Relatório de Testes com GitHub Pages 
        uses: actions/deploy-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: results/



